server.port=8083
spring.application.name=todoapp
# 1. Database Connection
spring.datasource.url=jdbc:sqlite:todo.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# 2. Hibernate / JPA Settings (The exact path for Spring Boot 3)
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# 3. SQLite specific fix for Hibernate 6
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect